// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Database.Migrations
{
    [DbContext(typeof(StrvTemplateDbContext))]
    internal class StrvTemplateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Database.Entities.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnName("name")
                    .HasMaxLength(255);

                b.Property<int>("ProductCategoryId")
                    .HasColumnName("product_category_id");

                b.HasKey("Id");

                b.HasIndex("ProductCategoryId");

                b.ToTable("products");
            });

            modelBuilder.Entity("Database.Entities.ProductCategory", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("id");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnName("name")
                    .HasMaxLength(255);

                b.HasKey("Id");

                b.ToTable("product_categories");
            });

            modelBuilder.Entity("Database.Entities.Product", b =>
            {
                b.HasOne("Database.Entities.ProductCategory", "ProductCategory")
                    .WithMany("Products")
                    .HasForeignKey("ProductCategoryId")
                    .OnDelete(DeleteBehavior.Restrict);
            });
#pragma warning restore 612, 618
        }
    }
}