version: '2.4'

services:

  web:
    container_name: 'aspnetcoreapp'
    image: 'aspnetcoreapp'
    build:
      context: .
    ports:
     - "5000:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - aspnetcoreapp-network

  postgres:
    container_name: 'postgres'
    image: postgres
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 2s
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge
